apiVersion: v1
kind: Service
metadata:
  labels:
    app: netshoe
  name: netshoe
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: netshoe
  type: ClusterIP
